### ISSUE TITLE
Add option to opt out of modern CSS transform properties like `scale`, `translate`, etc.

### ISSUE THREAD

**Issue by brandonmcconnell** [sambauers/tailwindcss-3d#17]
Many of my users still use Safari v13.x, which does not support the newer CSS transform-related properties like `scale`, `translate`, etc.

By default, this is fine, as TailwindCSS supports the older transform styles, in this way:

```html
<div class="scale-150 rotate-45"></div>
```

```css
.rotate-45 {
    --tw-rotate: 45deg;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}

.scale-150 {
    --tw-scale-x: 1.5;
    --tw-scale-y: 1.5;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
}
```

where each transform-related property applies the same foundational `transform` value:
```css
transform: 
  translate(var(--tw-translate-x), var(--tw-translate-y))
  rotate(var(--tw-rotate))
  skewX(var(--tw-skew-x))
  skewY(var(--tw-skew-y))
  scaleX(var(--tw-scale-x))
  scaleY(var(--tw-scale-y));
```

It'd be great if tailwindcss-3d could support 3d transforms but using the same syntax and impl-style as the existing TailwindCSS-native styles.

This could look something like this:

```html
<div class="scale-z-50 rotate-z-90 translate-z-44"></div>
```

```css
transform: 
  translate(var(--tw-translate-x), var(--tw-translate-y), var(--tw-translate-z))
  rotateX(var(--tw-rotate-x))
  rotateY(var(--tw-rotate-y))
  rotateZ(var(--tw-rotate, var(--tw-rotate)))
  skew(var(--tw-skew-x), var(--tw-skew-y))
  scale3d(var(--tw-scale-x, var(--tw-scale)), var(--tw-scale-y, var(--tw-scale)), var(--tw-scale-z, var(--tw-scale)));
```
